// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.33.1
// source: src/proto/command/domain/CpuMetrics.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "";

/**  */
export interface CpuMetrics {
  cpuLoad: number;
  processCpuLoad: number;
  oneMinuteLoadAverage: number;
  fiveMinuteLoadAverage: number;
  fifteenMinuteLoadAverage: number;
}

function createBaseCpuMetrics(): CpuMetrics {
  return {
    cpuLoad: 0,
    processCpuLoad: 0,
    oneMinuteLoadAverage: 0,
    fiveMinuteLoadAverage: 0,
    fifteenMinuteLoadAverage: 0,
  };
}

export const CpuMetrics = {
  encode(message: CpuMetrics, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.cpuLoad !== 0) {
      writer.uint32(9).double(message.cpuLoad);
    }
    if (message.processCpuLoad !== 0) {
      writer.uint32(17).double(message.processCpuLoad);
    }
    if (message.oneMinuteLoadAverage !== 0) {
      writer.uint32(25).double(message.oneMinuteLoadAverage);
    }
    if (message.fiveMinuteLoadAverage !== 0) {
      writer.uint32(33).double(message.fiveMinuteLoadAverage);
    }
    if (message.fifteenMinuteLoadAverage !== 0) {
      writer.uint32(41).double(message.fifteenMinuteLoadAverage);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CpuMetrics {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCpuMetrics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 9) {
            break;
          }

          message.cpuLoad = reader.double();
          continue;
        case 2:
          if (tag !== 17) {
            break;
          }

          message.processCpuLoad = reader.double();
          continue;
        case 3:
          if (tag !== 25) {
            break;
          }

          message.oneMinuteLoadAverage = reader.double();
          continue;
        case 4:
          if (tag !== 33) {
            break;
          }

          message.fiveMinuteLoadAverage = reader.double();
          continue;
        case 5:
          if (tag !== 41) {
            break;
          }

          message.fifteenMinuteLoadAverage = reader.double();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },
};
