// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.33.1
// source: src/proto/command/domain/HostInfo.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "cn.easii.tutelary.message.command.domain";

/**  */
export interface HostInfo {
  hostName: string;
  hostAddress: string;
  osName: string;
  arch: string;
  systemVersion: string;
  cpuModel: string;
  availableProcessors: number;
  systemBootTime: string;
  memorySize: number;
}

function createBaseHostInfo(): HostInfo {
  return {
    hostName: "",
    hostAddress: "",
    osName: "",
    arch: "",
    systemVersion: "",
    cpuModel: "",
    availableProcessors: 0,
    systemBootTime: "",
    memorySize: 0,
  };
}

export const HostInfo = {
  encode(message: HostInfo, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.hostName !== "") {
      writer.uint32(10).string(message.hostName);
    }
    if (message.hostAddress !== "") {
      writer.uint32(18).string(message.hostAddress);
    }
    if (message.osName !== "") {
      writer.uint32(26).string(message.osName);
    }
    if (message.arch !== "") {
      writer.uint32(34).string(message.arch);
    }
    if (message.systemVersion !== "") {
      writer.uint32(42).string(message.systemVersion);
    }
    if (message.cpuModel !== "") {
      writer.uint32(50).string(message.cpuModel);
    }
    if (message.availableProcessors !== 0) {
      writer.uint32(56).int32(message.availableProcessors);
    }
    if (message.systemBootTime !== "") {
      writer.uint32(66).string(message.systemBootTime);
    }
    if (message.memorySize !== 0) {
      writer.uint32(72).int64(message.memorySize);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): HostInfo {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.hostName = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.hostAddress = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.osName = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.arch = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.systemVersion = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.cpuModel = reader.string();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.availableProcessors = reader.int32();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.systemBootTime = reader.string();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.memorySize = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },
};

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}
