// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.33.1
// source: src/proto/command/domain/JvmInfo.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "";

/**  */
export interface JvmInfo {
  inputArguments: string[];
  environmentProperties: { [key: string]: string };
  classPath: string;
  libraryPath: string;
  vmVendor: string;
  vmName: string;
  vmVersion: string;
  jdkVersion: string;
  startTime: number;
  starter: string;
  javaRuntimeVersion: string;
  javaHome: string;
  pid: string;
}

export interface JvmInfo_EnvironmentPropertiesEntry {
  key: string;
  value: string;
}

function createBaseJvmInfo(): JvmInfo {
  return {
    inputArguments: [],
    environmentProperties: {},
    classPath: "",
    libraryPath: "",
    vmVendor: "",
    vmName: "",
    vmVersion: "",
    jdkVersion: "",
    startTime: 0,
    starter: "",
    javaRuntimeVersion: "",
    javaHome: "",
    pid: "",
  };
}

export const JvmInfo = {
  encode(message: JvmInfo, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.inputArguments) {
      writer.uint32(10).string(v!);
    }
    Object.entries(message.environmentProperties).forEach(([key, value]) => {
      JvmInfo_EnvironmentPropertiesEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).ldelim();
    });
    if (message.classPath !== "") {
      writer.uint32(26).string(message.classPath);
    }
    if (message.libraryPath !== "") {
      writer.uint32(34).string(message.libraryPath);
    }
    if (message.vmVendor !== "") {
      writer.uint32(42).string(message.vmVendor);
    }
    if (message.vmName !== "") {
      writer.uint32(50).string(message.vmName);
    }
    if (message.vmVersion !== "") {
      writer.uint32(58).string(message.vmVersion);
    }
    if (message.jdkVersion !== "") {
      writer.uint32(66).string(message.jdkVersion);
    }
    if (message.startTime !== 0) {
      writer.uint32(72).int64(message.startTime);
    }
    if (message.starter !== "") {
      writer.uint32(82).string(message.starter);
    }
    if (message.javaRuntimeVersion !== "") {
      writer.uint32(90).string(message.javaRuntimeVersion);
    }
    if (message.javaHome !== "") {
      writer.uint32(98).string(message.javaHome);
    }
    if (message.pid !== "") {
      writer.uint32(106).string(message.pid);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): JvmInfo {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJvmInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.inputArguments.push(reader.string());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          const entry2 = JvmInfo_EnvironmentPropertiesEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.environmentProperties[entry2.key] = entry2.value;
          }
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.classPath = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.libraryPath = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.vmVendor = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.vmName = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.vmVersion = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.jdkVersion = reader.string();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.startTime = longToNumber(reader.int64() as Long);
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.starter = reader.string();
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.javaRuntimeVersion = reader.string();
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.javaHome = reader.string();
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.pid = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },
};

function createBaseJvmInfo_EnvironmentPropertiesEntry(): JvmInfo_EnvironmentPropertiesEntry {
  return { key: "", value: "" };
}

export const JvmInfo_EnvironmentPropertiesEntry = {
  encode(message: JvmInfo_EnvironmentPropertiesEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): JvmInfo_EnvironmentPropertiesEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJvmInfo_EnvironmentPropertiesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },
};

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}
