// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.33.1
// source: src/proto/command/domain/MemoryMetrics.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "cn.easii.tutelary.message.command.domain";

/**  */
export interface MemoryMetrics {
  committedVirtualMemory: number;
  totalPhysicalMemorySize: number;
  freePhysicalMemorySize: number;
  totalSwapSpaceSize: number;
  freeSwapSpaceSize: number;
}

function createBaseMemoryMetrics(): MemoryMetrics {
  return {
    committedVirtualMemory: 0,
    totalPhysicalMemorySize: 0,
    freePhysicalMemorySize: 0,
    totalSwapSpaceSize: 0,
    freeSwapSpaceSize: 0,
  };
}

export const MemoryMetrics = {
  encode(message: MemoryMetrics, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.committedVirtualMemory !== 0) {
      writer.uint32(8).int64(message.committedVirtualMemory);
    }
    if (message.totalPhysicalMemorySize !== 0) {
      writer.uint32(16).int64(message.totalPhysicalMemorySize);
    }
    if (message.freePhysicalMemorySize !== 0) {
      writer.uint32(24).int64(message.freePhysicalMemorySize);
    }
    if (message.totalSwapSpaceSize !== 0) {
      writer.uint32(32).int64(message.totalSwapSpaceSize);
    }
    if (message.freeSwapSpaceSize !== 0) {
      writer.uint32(40).int64(message.freeSwapSpaceSize);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MemoryMetrics {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMemoryMetrics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.committedVirtualMemory = longToNumber(reader.int64() as Long);
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.totalPhysicalMemorySize = longToNumber(reader.int64() as Long);
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.freePhysicalMemorySize = longToNumber(reader.int64() as Long);
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.totalSwapSpaceSize = longToNumber(reader.int64() as Long);
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.freeSwapSpaceSize = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },
};

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}
