// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.33.1
// source: src/proto/command/domain/NetworkMetrics.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "cn.easii.tutelary.message.command.domain";

/**  */
export interface NetworkMetrics {
  bytesRecv: number;
  bytesSent: number;
  packetsRecv: number;
  packetsSent: number;
  recvSpeed: number;
  sendSpeed: number;
}

function createBaseNetworkMetrics(): NetworkMetrics {
  return { bytesRecv: 0, bytesSent: 0, packetsRecv: 0, packetsSent: 0, recvSpeed: 0, sendSpeed: 0 };
}

export const NetworkMetrics = {
  encode(message: NetworkMetrics, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.bytesRecv !== 0) {
      writer.uint32(8).int64(message.bytesRecv);
    }
    if (message.bytesSent !== 0) {
      writer.uint32(16).int64(message.bytesSent);
    }
    if (message.packetsRecv !== 0) {
      writer.uint32(24).int64(message.packetsRecv);
    }
    if (message.packetsSent !== 0) {
      writer.uint32(32).int64(message.packetsSent);
    }
    if (message.recvSpeed !== 0) {
      writer.uint32(40).int64(message.recvSpeed);
    }
    if (message.sendSpeed !== 0) {
      writer.uint32(48).int64(message.sendSpeed);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): NetworkMetrics {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNetworkMetrics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.bytesRecv = longToNumber(reader.int64() as Long);
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.bytesSent = longToNumber(reader.int64() as Long);
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.packetsRecv = longToNumber(reader.int64() as Long);
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.packetsSent = longToNumber(reader.int64() as Long);
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.recvSpeed = longToNumber(reader.int64() as Long);
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.sendSpeed = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },
};

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}
