// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.33.1
// source: src/proto/command/domain/OsFileStore.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "cn.easii.tutelary.message.command.domain";

/**  */
export interface OsFileStore {
  mount: string;
  totalSpace: number;
  usableSpace: number;
  type: string;
}

function createBaseOsFileStore(): OsFileStore {
  return { mount: "", totalSpace: 0, usableSpace: 0, type: "" };
}

export const OsFileStore = {
  encode(message: OsFileStore, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.mount !== "") {
      writer.uint32(10).string(message.mount);
    }
    if (message.totalSpace !== 0) {
      writer.uint32(16).int64(message.totalSpace);
    }
    if (message.usableSpace !== 0) {
      writer.uint32(24).int64(message.usableSpace);
    }
    if (message.type !== "") {
      writer.uint32(34).string(message.type);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): OsFileStore {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOsFileStore();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.mount = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.totalSpace = longToNumber(reader.int64() as Long);
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.usableSpace = longToNumber(reader.int64() as Long);
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.type = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },
};

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}
