// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.33.1
// source: src/proto/command/domain/ThreadStatistic.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "";

/**  */
export interface ThreadStatistic {
  threadCount: number;
  peakThreadCount: number;
  daemonThreadCount: number;
  totalStartedThreadCount: number;
  activeThreadCount: number;
  waitingThreadCount: number;
  blockedThreadCount: number;
}

function createBaseThreadStatistic(): ThreadStatistic {
  return {
    threadCount: 0,
    peakThreadCount: 0,
    daemonThreadCount: 0,
    totalStartedThreadCount: 0,
    activeThreadCount: 0,
    waitingThreadCount: 0,
    blockedThreadCount: 0,
  };
}

export const ThreadStatistic = {
  encode(message: ThreadStatistic, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.threadCount !== 0) {
      writer.uint32(8).int32(message.threadCount);
    }
    if (message.peakThreadCount !== 0) {
      writer.uint32(16).int32(message.peakThreadCount);
    }
    if (message.daemonThreadCount !== 0) {
      writer.uint32(24).int32(message.daemonThreadCount);
    }
    if (message.totalStartedThreadCount !== 0) {
      writer.uint32(32).int64(message.totalStartedThreadCount);
    }
    if (message.activeThreadCount !== 0) {
      writer.uint32(40).int32(message.activeThreadCount);
    }
    if (message.waitingThreadCount !== 0) {
      writer.uint32(48).int32(message.waitingThreadCount);
    }
    if (message.blockedThreadCount !== 0) {
      writer.uint32(56).int32(message.blockedThreadCount);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ThreadStatistic {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseThreadStatistic();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.threadCount = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.peakThreadCount = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.daemonThreadCount = reader.int32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.totalStartedThreadCount = longToNumber(reader.int64() as Long);
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.activeThreadCount = reader.int32();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.waitingThreadCount = reader.int32();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.blockedThreadCount = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },
};

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}
