/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'app',
    path: '/app',
    component: 'layout.base',
    meta: {
      title: 'app',
      i18nKey: 'route.app',
      activeMenu: 'app_list'
    },
    children: [
      {
        name: 'app_detail',
        path: '/app/detail/:appName',
        component: 'view.app_detail',
        meta: {
          title: 'app_detail',
          i18nKey: 'route.app_detail',
          hideInMenu: true,
          activeMenu: 'app_list'
        }
      },
      {
        name: 'app_instance',
        path: '/app/instance',
        meta: {
          title: 'app_instance',
          i18nKey: 'route.app_instance',
          hideInMenu: true
        },
        children: [
          {
            name: 'app_instance_detail',
            path: '/app/instance/detail/:instanceId',
            component: 'view.app_instance_detail',
            meta: {
              title: 'app_instance_detail',
              i18nKey: 'route.app_instance_detail',
              hideInMenu: true,
              activeMenu: 'app_list'
            }
          }
        ]
      },
      {
        name: 'app_list',
        path: '/app/list',
        component: 'view.app_list',
        meta: {
          title: 'app_list',
          i18nKey: 'route.app_list',
          icon: 'icon-park-solid:more-app'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base',
    meta: {
      title: 'log',
      i18nKey: 'route.log'
    },
    children: [
      {
        name: 'log_operation',
        path: '/log/operation',
        component: 'view.log_operation',
        meta: {
          title: 'log_operation',
          i18nKey: 'route.log_operation'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  }
];
