syntax="proto3";

import "src/proto/command/domain/GarbageCollector.proto";
import "src/proto/command/domain/ThreadStatistic.proto";
import "src/proto/command/domain/JvmMemory.proto";
import "src/proto/command/domain/HostInfo.proto";
import "src/proto/command/domain/BaseThreadInfo.proto";

//
message Overview {  
 HostInfo hostInfo=1;
 ThreadStatistic threadStatistic=2;
repeated BaseThreadInfo threads=3;
repeated JvmMemory heapMemory=4;
repeated JvmMemory nonHeapMemory=5;
repeated GarbageCollector garbageCollectors=6;
 int32 jobId=7;
 int32 state=8;
 string message=9;
}
